services:
  - type: web
    name: kingfisherai-api
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn backend.app.main:app --host 0.0.0.0 --port $PORT"
    autoDeploy: true
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: ENV
        value: production
