# Ruff configuration for Kingfisher API
line-length = 120
target-version = "py310"

[lint]
select = ["E", "F", "W", "I", "N", "UP", "B", "A", "C4", "SIM"]
ignore = ["E501"]  # Line too long (handled by formatter)

[lint.per-file-ignores]
"__init__.py" = ["F401"]  # Unused imports OK in __init__
"tests/*" = ["F401", "F811"]  # Test fixtures

